CREATE TABLE FHProduto (
    CODIGO VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    TIPO NUMERIC,
    VALOR_COMPRA NUMERIC(15, 2),
    VALOR_VENDA NUMERIC(15, 2),
    DATA_INCLUSAO DATE,
    DATA_ALTERACAO DATE,
    ATIVO BOOLEAN
);
