services:
  # BANCOS DE DADOS
  db:
    image: postgres
    container_name: ezband_db_dev
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - ezband_app_network
  
  mongodb:
    image: mongo:latest
    container_name: chat-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - ezband_app_network

  # STORAGE
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API S3
      - "9090:9090"   # Console web
    volumes:
      - ~/minio/data:/data
    env_file: .env
    networks:
      - ezband_app_network
    environment:
      MINIO_ROOT_USER: ${MINIO_ADMIN_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ADMIN_PASSWORD}
    command: server /data --console-address ":9090"

  minio-backup:
    image: quay.io/minio/minio:latest
    container_name: minio_backup
    ports:
      - "9100:9000"   # API S3 do backup
      - "9190:9090"   # Console web do backup
    volumes:
      - ~/minio-backup/data:/data
    env_file: .env
    networks:
      - ezband_app_network
    environment:
      MINIO_ROOT_USER: ${MINIO_BACKUP_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_BACKUP_PASSWORD}
    command: server /data --console-address ":9090"
  
  # APLICACOES
  chat-service:
    build: ./ChatService # caminho do seu microservice
    container_name: chat-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      PORT: 3001
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/chat?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - ezband_app_network

     # MinIO secundário (armazenamento dos backups)

  api:
    build: 
      context: ./EzBand-Backend
      dockerfile: Dockerfile
    container_name: ezband_backend_dev
    depends_on:
      - db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    networks:
      - ezband_app_network
    volumes:
      - app_logs_dev:/app/logs

  # BACKUP 
  backup:
    build: ./BackupService
    container_name: ezband_backup
    depends_on:
      - db
      - mongodb
      - minio
      - minio-backup
    volumes:
      - postgres_data_dev:/data/postgres:ro
      - mongo-data:/data/mongo:ro
      - app_logs_dev:/data/logs:ro
      - ./backup-temp:/backup
    env_file: .env
    networks:
      - ezband_app_network


volumes:
  postgres_data_dev:
  app_logs_dev:
  mongo-data:

networks:
  ezband_app_network:
    driver: bridge