ALTER TABLE usuario
ADD COLUMN IF NOT EXISTS end_pais VARCHAR(100),
ADD COLUMN IF NOT EXISTS end_estado VARCHAR(100),
ADD COLUMN IF NOT EXISTS end_bairro VARCHAR(100),
ADD COLUMN IF NOT EXISTS end_rua VARCHAR(255),
ADD COLUMN IF NOT EXISTS end_numero VARCHAR(20),
ADD COLUMN IF NOT EXISTS end_cep VARCHAR(20),
ADD COLUMN IF NOT EXISTS end_complemento VARCHAR(255);
